experiment:
  name: "PsychoPy Experiment"
  author: "Anna"
  description: "Museum painting selection task"

window:
  size: [800, 600]
  color: "black"
  units: "pix"
  fullscreen: False

# define screens for windows
winA: 0
winB: 0

files:
  output_folder: "output/"
  noise_soc: "C:\\Users\\VICON\\Desktop\\Code\\psychopyMuseum\\psychopyMuseum\\noise_folder\\background_noise_30"
  noise_nonsoc: "C:\\Users\\VICON\\Desktop\\Code\\psychopyMuseum\\psychopyMuseum\\noise_folder\\pink_noise_30"

input:
  key_1: "a"
  key_2: "w"
  key_3: "s"
  key_4: "d"

timing:
  intro_duration: 5
  instructions_duration: 30
  description_duration: 5

no_obs: True

obs_host:
  target_host: "192.168.0.166" # ip address of my pc
  target_port: 4444

# Of the location to send the files to after they are recorded
receiver_machine:
  ip: '192.168.0.180'
  port: 4422

# obs_connection:
#   no_obs: True
#   obs_host: 'localhost'
#   obs_port: 4457
#   # Leave empty if no password is set
#   obs_password:

python_path: 'C:/Users/VICON/.pyenv/pyenv-win/versions/3.10.11/python.exe'
receiver_script_path: 'C:\Users\VICON\Desktop\Code\OBSRecorder\OBSRecorder\src\src_sendAndReceive\receiveFiles.py'
