experiment:
  name: "PsychoPy Experiment"
  author: "Anna"
  description: "Museum painting selection task"

window:
  size: [800, 600]
  color: "black"
  units: "pix"
  fullscreen: False

# define screens for windows
winA: 0
winB: 0

files:
  output_folder: "output/"
  noise_soc: "C:/Users/apalman/OneDrive - UvA/Desktop/noise_files/background_noise_30"
  noise_nonsoc: "C:/Users/apalman/OneDrive - UvA/Desktop/noise_files/pink_noise_30"

input:
  key_1: "a"
  key_2: "w"
  key_3: "s"
  key_4: "d"

timing:
  intro_duration: 5
  instructions_duration: 30
  description_duration: 5

obs_host: 
  target_host: "192.168.0.211" # ip address of my pc
  target_port: 4422

# Of the location to send the files to after they are recorded
receiver_machine:
  ip: '192.168.0.180'
  port: 4422

obs_connection:
  no_obs: True
  obs_host: 'localhost'
  obs_port: 4457
  # Leave empty if no password is set
  obs_password:

