experiment:
  name: "PsychoPy Experiment"
  author: "Anna"
  description: "Museum painting selection task"

window:
  size: [800, 600]
  color: "black"
  units: "pix"
  fullscreen: True

# define screens for windows
winA: 2
winB: 1

files:
  output_folder: "output/obs/"
  obs_buffer_folder: "D:\\Anna\\mkv\\SourceRecordBuffer"
  # noise_soc: "C:\\Users\\apalman\\OneDrive - UvA\\Desktop\\noise_files\\background_noise_30.wav"
  # noise_nonsoc: "C:\\Users\\apalman\\OneDrive - UvA\\Desktop\\noise_files\\pink_noise_30.wav"
# Jari PC paths:
  noise_soc: ["D:\\Anna\\noise\\noise_soc_10.wav", 1.0]
  noise_nonsoc: ["D:\\Anna\\noise\\pink_noise_10.wav", 1.0]

# Anna PC paths
# noise_soc: "C:/Users/apalman/OneDrive - UvA/Desktop/noise_files/background_noise_30"
# noise_nonsoc: "C:/Users/apalman/OneDrive - UvA/Desktop/noise_files/pink_noise_30"

no_obs: False

input:
  key_1: "a"
  key_2: "w"
  key_3: "s"
  key_4: "d"

timing:
  intro_duration: 5
  instructions_duration: 30
  description_duration: 5


obs_host:
  target_host: "localhost" # ip address of my pc
  target_port: 4444

# Of the location to send the files to after they are recorded
receiver_machine:
  ip: 'localhost'
  port: 4444

# obs_connection:
#   no_obs: True
#   obs_host: 'localhost'
#   obs_port: 4457
#   # Leave empty if no password is set
#   obs_password:

#Jari paths
python_path: 'C:\Users\vislab\AppData\Local\Programs\Python\Python311\python.exe'
receiver_script_path: 'D:\Anna\Code\psychopyMuseum\src\OBSRecorder\src\src_sendAndReceive\receiveFiles.py'

#Anna paths
# python_path: "C:/Program Files/Python39/python.exe"