experiment:
  name: "PsychoPy Experiment"
  author: "Your Colleague's Name"
  description: "Museum painting selection task"

window:
  size: [800, 600]
  color: "black"
  units: "pix"
  fullscreen: false

files:
  output_folder: "output/"
  # output_folder: "C:/Users/apalman/OneDrive - UvA/Desktop/"
  output_file: "output_round2.csv"
  img_folder: "img_folder/artworks/"
  img_folder_museum: "img_folder/museumImages/"
  img_4pics: "museum_4pics.jpeg"
  img_text: "museum_text.jpeg"
  stimuli_folder: "stim_folder/"
  stimuli_excel: "stimuli_round2.xlsx"
  noise_folder: "noise_folder/"
  noise_soc_10: "noise_soc_10"
  noise_soc_30: "noise_soc_30"
  pink_noise_10: "pink_noise_10"
  pink_noise_30: "pink_noise_30"

input:
  key_1: "a"
  key_2: "w"
  key_3: "s"
  key_4: "d"

timing:
  intro_duration: 5
  instructions_duration: 60
  description_duration: 5

randomization:
  shuffle_images: true  # If false, keep a fixed order
