experiment:
  name: "PsychoPy Experiment"
  author: "Your Colleague's Name"
  description: "Museum painting selection task"

window:
  size: [800, 600]
  color: "black"
  units: "pix"
  fullscreen: false

files:
  output_folder: "output/"
  # output_folder: "C:/Users/apalman/OneDrive - UvA/Desktop/"
  output_file: "output_round2.csv"
  img_folder: "img_folder/artworks/"
  img_folder_museum: "img_folder/museumImages/"
  img_4pics: "museum_4pics.jpeg"
  img_text: "museum_text.jpeg"
  stimuli_folder: "stim_folder/"
  stimuli_excel: "stimuli_round2.xlsx"
  noise_folder: "noise_folder/"
  noise_soc_10: "background_noise_10"
  noise_soc_30: "background_noise_30"
  pink_noise_10: "pink_noise_10"
  pink_noise_30: "pink_noise_30"

input:
  key_1: "a"
  key_2: "w"
  key_3: "s"
  key_4: "d"

timing:
  intro_duration: 5
  instructions_duration: 60
  description_duration: 5

randomization:
  shuffle_images: true  # If false, keep a fixed order

obs_host: 
  target_host: "192.168.0.211" # ip address of my pc
  target_port: 4422

# Of the location to send the files to after they are recorded
receiver_machine:
  ip: '192.168.0.180'
  port: 4422

obs_connection:
  no_obs: True
  obs_host: 'localhost'
  obs_port: 4457
  # Leave empty if no password is set
  obs_password:

