texts:
    instr: "In deze opdracht zien jullie korte beschrijvingen van abstracte schilderijen op het scherm. Stel jullie voor dat jullie bij een museumbezoek zijn en de gids beschrijft een schilderij aan jullie. Druk op een knop om verder te gaan, daarna zien jullie vier verschillende schilderijen op het scherm. Het is jullie taak om samen te overleggen en te beslissen welk van de vier schilderijen de gids heeft beschreven. Als jullie dat hebben besloten, gebruiken jullie de knoppen om een schilderij te selecteren. Dan verschijnt de volgende beschrijving.\nDruk op een knop om te beginnen."
    switch: null
    
images:
  img_folder: "img_folder/"
  img4_background: "museumImages/museum_4pics.jpeg"
  img1_background: null
  text_background: "museumImages/museum_text.jpeg"

stimuli:
    stim_file: "stim_folder/stimuli_round2.xlsx"

role_switch: False
show_target: False