texts:
    instr: "In deze opdracht zien jullie korte beschrijvingen van abstracte schilderijen op het scherm. \n\nStel jullie voor dat jullie bij een museumbezoek zijn en de gids beschrijft een schilderij aan jullie. \n\nDaarna zien jullie vier verschillende schilderijen op het scherm. Het is jullie taak om samen te overleggen en te beslissen welk van de vier schilderijen de gids heeft beschreven. \n\nAls jullie dat hebben besloten, gebruiken jullie het knoppenvak om een schilderij te selecteren. Dan verschijnt de volgende beschrijving.", color="white", height=30, wrapWidth=600)"

images:
  4image_background: "img_folder/museumImages/museum_4pics.jpeg"
  1image_background: null
  text_background: "img_folder/museumImages/museum_text.jpeg"

stimuli:
    stim_file: "stim_folder/stimuli_round2.xlsx"

